platforms = [
    "Node.js",
    "Frontend Development",
    "iOS",
    "Android",
    "IoT & Hybrid Apps",
    "Electron",
    "Cordova",
    "React Native",
    "Xamarin",
    "Linux",
    "Containers",
    "macOS",
    "Command-Line",
    "Screensavers",
    "watchOS",
    "JVM",
    "Salesforce",
    "Amazon Web Services",
    "Windows",
    "IPFS",
    "Fuse",
    "Heroku",
    "Raspberry Pi"
    ]

languages = [
    "JavaScript",
    "Swift",
    "Python",
    "Rust",
    "Haskell",
    "PureScript",
    "Go",
    "Scala",
    "Ruby",
    "Clojure",
    "ClojureScript",
    "Elixir",
    "Elm",
    "Erlang",
    "Julia",
    "Lua",
    "C",
    "C/C++",
    "R",
    "D",
    "Common Lisp",
    "Perl",
    "Groovy",
    "Dart",
    "Java",
    "Kotlin",
    "OCaml",
    "ColdFusion",
    "Fortran",
    ".NET",
    "PHP",
    "Delphi",
    "Assembler",
    "AutoHotkey",
    "AutoIt",
    "Crystal",
    "TypeScript",
    "Frege",
    "CMake"
    ]
